### ISSUE TITLE
Why Travis ci?

### ISSUE THREAD

**Issue by Hampusm** [KartSriv/Story#18]
Why did you create a Travis ci for this?
This isnt something that can be run. 
`language: python`
Its a story not a Python project.

What are you thinking?
We dont need Travis ci

**Comment by KartSriv** [comment]
@Hampusm I am AFK! I thought of creating a Python Script to automate PR checks.

**Comment by Hampusm** [comment]
@KartSriv Nice. I could help. Maybe open a issue for it?
And also, a tip is to make the Travis ci after you have made it

**Comment by KartSriv** [comment]
Sorry, @Hampusm! I was working on it this morning but due to studies, I gotta go AFK. It's a bloody pain to accept PR for Stories cause when a lot of them come at the same time people will just add a line in the same position which will cause coalition. I think I should delete travis.yml cause I don't think I can do it soon. Life sometimes sucks when you are a student.

**Comment by KartSriv** [comment]
@Hampusm Just noticed you change your profile picture all the time xD
